apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vocal-cockroach-python 
  janus-idp.io/tekton: vocal-cockroach-python
  backstage.io/kubernetes-id: vocal-cockroach-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vocal-cockroach-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  