apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vocal-cockroach-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vocal-cockroach-python 
  name: vocal-cockroach-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vocal-cockroach-python 
